# CS 115 - Introduction to Programming in Python
## Lab 06

### Lab Objectives:  Two-D Lists, numpy arrays

**Instructions:** 
- In this lab, you will use Jupyter Notebook. Write your solutions in this notebook, put it in a .zip file named SS_Lab06_Surname_FirstName.zip where SS is the section number 01, 02, 03, etc. and upload it to the Lab06 assignment for your section on Moodle by 17:30 on Friday, November 27. 
- In Question 2, do not use any loops; you should only use numpy functions.
- Solutions sent through email will not be accepted.
- You should only use functionality covered in CS115 in your solution.


## <font color=red>Question 1</font> 
### You will write code to store and manipulate two dimensional lists of data. Complete the steps below.

Write a function, ***sum_lower()*** that takes a two-dimensional list of integers as a parameter.  The function should return the sum of the lower triangular elements.

In [1]:
##function to return sum of lower tiangular matrix
def sum_lower(matt):
    ans = 0
    for row in range(len(matt)):
        for column in range(len(matt[row])):
            if(column<=row):
                ans+=matt[row][column]
    return ans

Write a function, ***sum_major()*** that takes a two-dimensional list of integers as a parameter.  The function should return the sum of the major diagonal elements.

In [2]:
##function to return Sum of the major diagonal element
def sum_major(matt):
    ans = 0
    for row in range(len(matt)):
        for column in range(len(matt[row])):
            if(column==row):
                ans+=matt[row][column]
    return ans

Using the function above write code that initializes a two dimensional list of integer values, and displays the data shown in the sample run below.

Sample Run:

Table:

[3, 4, 8, 6]

[6, 2, 2, 5]

[8, 7, 7, 9]

[4, 6, 2, 3]

Sum of the lower triangular elements:  48

Sum of the major diagonal elements:  15



In [3]:
matt = [[3,4,8,6],[6,2,2,5],[8,7,7,9],[4,6,2,3]]
print('table:')
for row in range(len(matt)):
    print(matt[row])
print("Sum of Lower Triangular element : ",sum_lower(matt))
print("Sum of the major diagonal element : ",sum_major(matt))

table:
[3, 4, 8, 6]
[6, 2, 2, 5]
[8, 7, 7, 9]
[4, 6, 2, 3]
Sum of Lower Triangular element :  48
Sum of the major diagonal element :  15


## <font color=red>Question 2</font> 
### You will use numpy arrays to store and manipulate data from files.  Do no use any loops. Complete the steps listed below:

import numpy for use in your code

In [1]:
import numpy as np

Read data from the files grades.txt and weights.txt into two numpy arrays.  The file grades.txt contains an array of student exam grades.  Each row in the file stores the scores for each student (Quiz1, Quiz2, Homework, Midterm, Final). The file weights.txt stores the exam weights for each assessment. After inputting the weights, they should be converted to a decimal percentage. Ex 10% becomes 0.10.

In [2]:
grades=np.loadtxt('grades.txt',skiprows=1)
weights=np.loadtxt('weights.txt',skiprows=2)
weights/=100

Display the grades and the weights.

In [3]:
print(grades)
print(weights)

[[ 70.  67.  85.  92.  75.]
 [ 80.  76.  90.  86.  88.]
 [ 60.  82.  45.  71.  68.]
 [ 88.  92.  77.  64.  80.]
 [100.  97. 100.  92.  85.]
 [ 74.  51.  62.  43.  79.]]
[0.1  0.1  0.15 0.3  0.35]


Sum the grades for each assessment and store in a new array.

In [5]:
sum_of_grades=np.array(np.sum(grades,axis=0))
print(sum_of_grades)

[472. 465. 459. 448. 475.]


Calculate the average score for each assessment and store in a new array. Hint: use the sums calculated above.

In [5]:
avrg_grades=np.array(np.mean(grades,axis=0))
print(avrg_grades)

[78.66666667 77.5        76.5        74.66666667 79.16666667]


Calculate and display the average overall score. The overall score can be found by multiplying the weights of the 
assessments by the average score for each assesssment.

In [6]:
overall=np.array(np.dot(avrg_grades,weights))
print(overall)

77.2


Calculate the overall grades for each student and store in an array.  Write the array to the file student_overall.txt

In [8]:
overall_grades=np.array(np.sum(grades*weights,axis=1))
np.savetxt('student_overall.txt',overall_grades,fmt='%.2f')